name: Attic cache
description: Authenticate with Attic and upload paths built during the job

inputs:
  token:
    description: Attic token
    required: true
  server:
    description: Attic server URL
    required: false
    default: https://attic.osipol.uk
  cache:
    description: Attic cache name
    required: false
    default: cache
runs:
  using: composite
  steps:
    - name: Authenticate with Attic
      shell: bash
      env:
        ATTIC_TOKEN: ${{ inputs.token }}
        ATTIC_SERVER: ${{ inputs.server }}
      run: nix run nixpkgs#attic-client -- login local "$ATTIC_SERVER" "$ATTIC_TOKEN"

    - name: Watch Nix store
      shell: bash
      env:
        ATTIC_CACHE: ${{ inputs.cache }}
      run: setsid nix run nixpkgs#attic-client -- watch-store "$ATTIC_CACHE" < /dev/null > /dev/null 2>&1 &
