# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ ];

  boot.initrd.availableKernelModules = [ "ehci_pci" "ahci" "xhci_pci" "nvme" "usbhid" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/49ba33f4-591e-477c-bca6-c9bcebb429d7";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/A46E-006E";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/mnt/hgfs" =
    { device = "vmhgfs-fuse";
      fsType = "fuse.vmhgfs-fuse";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/b9f8411a-2b49-4821-a8dd-efe9883a54cf"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}
