{inputs, ...}: {
  perSystem = {
    lib,
    pkgs,
    ...
  }: let
    nixosAnywhere = inputs.nixos-anywhere.packages.${pkgs.stdenv.hostPlatform.system}.default;
  in {
    packages = lib.optionalAttrs pkgs.stdenv.hostPlatform.isLinux {
      # tumblr-to-ebook: Convert a backup generated by tumblr-backup into an ebook
      tumblr-to-ebook = pkgs.writeShellApplication {
        name = "tumblr-to-ebook";
        runtimeInputs = [
          pkgs.coreutils
          pkgs.findutils
          pkgs.gnused
          pkgs.calibre
        ];
        text = ''
          usage() {
            echo "Usage: $0 <backup_dir> <title> <author> <output.epub> [--begin YYYY-MM] [--end YYYY-MM]"
          }

          BEGIN=""
          END=""
          POSITIONAL=()

          while [ "$#" -gt 0 ]; do
            case "$1" in
              --begin)
                BEGIN="''${2:?Error: --begin requires a YYYY-MM value}"
                shift 2
                ;;
              --end)
                END="''${2:?Error: --end requires a YYYY-MM value}"
                shift 2
                ;;
              --help)
                usage
                exit 0
                ;;
              *)
                POSITIONAL+=("$1")
                shift
                ;;
            esac
          done

          [ "''${#POSITIONAL[@]}" -eq 4 ] || {
            usage >&2
            exit 1
          }

          BLOG_DIR="''${POSITIONAL[0]}"
          TITLE="''${POSITIONAL[1]}"
          AUTHOR="''${POSITIONAL[2]}"
          OUT="''${POSITIONAL[3]}"

          [[ -z "$BEGIN" || "$BEGIN" =~ ^[0-9]{4}-[0-9]{2}$ ]] || {
            echo "Error: --begin must be in YYYY-MM format." >&2
            exit 1
          }
          [[ -z "$END" || "$END" =~ ^[0-9]{4}-[0-9]{2}$ ]] || {
            echo "Error: --end must be in YYYY-MM format." >&2
            exit 1
          }
          [[ -z "$BEGIN" || -z "$END" || "$BEGIN" < "$END" || "$BEGIN" == "$END" ]] || {
            echo "Error: --begin must not be after --end." >&2
            exit 1
          }

          ARCHIVE_DIR="$BLOG_DIR/archive"
          COMBINED="$BLOG_DIR/_combined.html"
          COVER="$BLOG_DIR/theme/avatar.jpg"

          [ -d "$ARCHIVE_DIR" ] || {
            echo "Error: $ARCHIVE_DIR not found. Check the backup_dir path." >&2
            exit 1
          }

          echo "Combining archive pages in chronological order..."
          {
            printf '<html><head><meta charset="utf-8"><title>%s</title></head><body>\n' "$TITLE"
            while IFS= read -r f; do
              filename="''${f##*/}"
              month="''${filename:0:7}"
              if { [ -n "$BEGIN" ] && [[ "$month" < "$BEGIN" ]]; } || { [ -n "$END" ] && [[ "$month" > "$END" ]]; }; then
                continue
              fi
              printf '<div class="pagebreak">\n'
              sed -e 's:\.\./media:media:g' -e 's:\.\./backup:backup:g' "$f"
              printf '</div>\n'
            done < <(find "$ARCHIVE_DIR" -maxdepth 1 -name '????-??-p*.html' | sort)
            printf '</body></html>\n'
          } > "$COMBINED"

          echo "Converting to ebook with Calibre..."
          ARGS=(
            "$COMBINED" "$OUT"
            --title "$TITLE"
            --authors "$AUTHOR"
            --level1-toc "//h:h1"
            --level2-toc "//h:h2"
            --chapter-mark none
          )

          [ -f "$COVER" ] && ARGS+=(--cover "$COVER")

          ebook-convert "''${ARGS[@]}"

          echo "Done: $OUT"
        '';
      };

      # install: Bootstrap a machine with nixos-anywhere
      install = pkgs.writeShellApplication {
        name = "install";
        runtimeInputs = [
          pkgs.coreutils
          pkgs.nix
          pkgs.openssh
          pkgs.ssh-to-age
          nixosAnywhere
        ];
        text = ''
          if [ "$#" -lt 2 ]; then
            echo "Usage: $0 <target-ip> <hostname> [facter-path]"
            echo "Example: $0 192.168.1.100 able-archer $HOME/Coding/nixos-secrets/facter/$HOSTNAME.json"
            exit 1
          fi

          TARGET_IP=$1
          HOSTNAME=$2
          FACTER_PATH="''${3:-$HOME/Coding/nixos-secrets/facter/$HOSTNAME.json}"
          USER_RUN_DIR="/run/user/$(id -u)"
          TMP_DIR=$(mktemp -d "$USER_RUN_DIR/nixos-anywhere-deploy.XXXXXX")

          cleanup() {
            if [ -d "$TMP_DIR" ]; then
              rm -rf "$TMP_DIR"
            fi
          }
          trap cleanup EXIT

          PERSISTENT_ETC_SSH_DIR="$TMP_DIR/persistent/etc/ssh"
          HOST_KEY_PATH="$PERSISTENT_ETC_SSH_DIR/ssh_host_ed25519_key"

          echo "========================================================="
          echo "Generating facter report..."
          echo "========================================================="
          # Based on https://github.com/nix-community/nixos-anywhere/blob/ad8fa24e11eef167fd72d49fafefa3f840312d71/src/nixos-anywhere.sh
          nix_options=(
            --extra-experimental-features 'nix-command flakes'
            "--no-write-lock-file"
          )
          mkdir -p "$(dirname "$FACTER_PATH")"
          ssh "root@$TARGET_IP" \
            nix shell "''${nix_options[@]@Q}" nixpkgs#nixos-facter -c nixos-facter > "$FACTER_PATH"
          echo "Path: $FACTER_PATH"

          echo
          echo "========================================================="
          echo "Generating SSH host keys..."
          echo "========================================================="

          mkdir -p "$PERSISTENT_ETC_SSH_DIR"
          ssh-keygen -t ed25519 -f "$HOST_KEY_PATH" -N "" -q

          echo
          echo "========================================================="
          echo "Generating age public key..."
          echo "========================================================="
          AGE_PUBLIC_KEY=$(ssh-to-age -i "$HOST_KEY_PATH.pub")
          echo "Key: $AGE_PUBLIC_KEY"
          echo "Configure secrets for this key in the secrets repo and push the changes."
          echo

          deploy_cmd=(
            nixos-anywhere
            --flake ".#$HOSTNAME"
            --extra-files "$TMP_DIR"
            --build-on remote
            "root@$TARGET_IP"
          )

          while true; do
            while true; do
              read -r -p "Update secrets input? (y/n): " choice_update
              case "$choice_update" in
                [Yy]*)
                  nix flake update secrets
                  break
                  ;;
                [Nn]*)
                  echo "Please configure your secrets first."
                  ;;
                *)
                  echo "Please answer y or n."
                  ;;
              esac
            done

            echo
            echo "========================================================="
            echo "Preparing to deploy..."
            echo "========================================================="
            echo "Target IP: $TARGET_IP"
            echo "Hostname:  $HOSTNAME"
            echo "Command to execute:"
            echo "  ''${deploy_cmd[*]}"
            echo

            while true; do
              read -r -p "Start deploy? (y/n): " choice_deploy
              case "$choice_deploy" in
                [Yy]*)
                  "''${deploy_cmd[@]}"
                  break 2
                  ;;
                [Nn]*)
                  break
                  ;;
                *)
                  echo "Please answer y or n."
                  ;;
              esac
            done
          done
        '';
      };
    };
  };
}
