name: Build Configurations
description: Build all NixOS configurations & push to binary cache

on:
  workflow_dispatch:
  pull_request:

jobs:
  find-configurations:
    if: >-
      github.event_name == 'workflow_dispatch' ||
      (
        github.event_name == 'pull_request' &&
        contains(github.event.pull_request.labels.*.name, 'automated') &&
        contains(github.event.pull_request.labels.*.name, 'flake-update')
      )
    runs-on: ubuntu-latest
    outputs:
      configurations: ${{ steps.find-configurations.outputs.configurations }}
    steps:
      - uses: actions/checkout@v7
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.READ_NIXOS_SECRETS_GITHUB_TOKEN }}

      - name: Find configuration names and runners
        id: find-configurations
        run: |
          configurations=$(nix eval .#nixosConfigurations \
            --apply '
              configs:
              let
                runnerForSystem = {
                  "x86_64-linux" = "ubuntu-latest";
                  "aarch64-linux" = "ubuntu-26.04-arm";
                };
              in
                builtins.map
                  (name:
                    let
                      config = configs.${name};
                      system = config.pkgs.stdenv.hostPlatform.system;
                    in {
                      attr = ".#nixosConfigurations.${name}.config.system.build.toplevel";
                      runner = runnerForSystem.${system};
                    })
                  (builtins.attrNames configs)
            ' \
            --json)
          echo "configurations=$configurations" >> "$GITHUB_OUTPUT"

  build-configurations:
    needs: find-configurations
    # Only runs on a flake update
    if: >-
      github.event_name == 'workflow_dispatch' ||
      (
        github.event_name == 'pull_request' &&
        contains(github.event.pull_request.labels.*.name, 'automated') &&
        contains(github.event.pull_request.labels.*.name, 'flake-update')
      )

    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJSON(needs.find-configurations.outputs.configurations) }}

    uses: ./.github/workflows/build-with-attic.yml
    with:
      runs-on: ${{ matrix.runner }}
      target: ${{ matrix.attr }}
    secrets:
      GITHUB_ACCESS_TOKEN: ${{ secrets.READ_NIXOS_SECRETS_GITHUB_TOKEN }}
      TS_OAUTH_CLIENT_ID: ${{ secrets.TS_OAUTH_CLIENT_ID }}
      TS_OAUTH_SECRET: ${{ secrets.TS_OAUTH_SECRET }}
      ATTIC_TOKEN: ${{ secrets.ATTIC_TOKEN }} 
