name: Build Configurations
description: Build all NixOS configurations & push to binary cache

on:
  workflow_dispatch:
  pull_request:

jobs:
  build-configurations:
    # Only runs on a flake update
    if: >-
      contains(github.event.pull_request.labels.*.name, 'automated') &&
      contains(github.event.pull_request.labels.*.name, 'flake-update')

    strategy:
      fail-fast: false
      matrix:
        include:
          - target: "able-archer"
            attr: ".#nixosConfigurations.able-archer.config.system.build.toplevel"
            runner: ubuntu-24.04-arm
          - target: "iron-hammer"
            attr: ".#nixosConfigurations.iron-hammer.config.system.build.toplevel"
            runner: ubuntu-latest
          - target: "steadfast-dart"
            attr: ".#nixosConfigurations.steadfast-dart.config.system.build.toplevel"
            runner: ubuntu-latest
          - target: "steadfast-defender"
            attr: ".#nixosConfigurations.steadfast-defender.config.system.build.toplevel"
            runner: ubuntu-latest
          - target: "iso-aarch64"
            attr: ".#packages.aarch64-linux.iso-system"
            runner: ubuntu-24.04-arm
          - target: "iso-x86_64"
            attr: ".#packages.x86_64-linux.iso-system"
            runner: ubuntu-latest
          - target: "mirage-red"
            attr: ".#nixosConfigurations.mirage-red.config.system.build.toplevel"
            runner: ubuntu-latest
          - target: "mirage-blue"
            attr: ".#nixosConfigurations.mirage-blue.config.system.build.toplevel"
            runner: ubuntu-latest

    uses: ./.github/workflows/build-with-attic.yml
    with:
      runs-on: ${{ matrix.runner }}
      target: ${{ matrix.attr }}
    secrets:
      GITHUB_ACCESS_TOKEN: ${{ secrets.READ_NIXOS_SECRETS_GITHUB_TOKEN }}
      TS_OAUTH_CLIENT_ID: ${{ secrets.TS_OAUTH_CLIENT_ID }}
      TS_OAUTH_SECRET: ${{ secrets.TS_OAUTH_SECRET }}
      ATTIC_TOKEN: ${{ secrets.ATTIC_TOKEN }} 

