name: Build ISOs
description: Build ISOs & push to binary cache

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  build-isos:
    # Only run on flake update PRs
    if: >-
      github.event_name != 'pull_request' ||
      (
        contains(github.event.pull_request.labels.*.name, 'automated') &&
        contains(github.event.pull_request.labels.*.name, 'flake-update')
      )
    strategy:
      fail-fast: false
      matrix:
        include:
          - attr: ".#packages.x86_64-linux.iso-system"
            runner: ubuntu-latest
          - attr: ".#packages.aarch64-linux.iso-system"
            runner: ubuntu-26.04-arm
        
    uses: ./.github/workflows/build-with-attic.yml
    with:
      runs-on: ${{ matrix.runner }}
      target: ${{ matrix.attr }}
    secrets:
      GITHUB_ACCESS_TOKEN: ${{ secrets.READ_NIXOS_SECRETS_GITHUB_TOKEN }}
      TS_OAUTH_CLIENT_ID: ${{ secrets.TS_OAUTH_CLIENT_ID }}
      TS_OAUTH_SECRET: ${{ secrets.TS_OAUTH_SECRET }}
      ATTIC_TOKEN: ${{ secrets.ATTIC_TOKEN }} 
