name: Build Packages
description: Build all custom packages & push to binary cache

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  find-packages:
    # Only run on flake update PRs
    if: >-
      github.event_name != 'pull_request' ||
      (
        contains(github.event.pull_request.labels.*.name, 'automated') &&
        contains(github.event.pull_request.labels.*.name, 'flake-update')
      )
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.find-packages.outputs.packages }}
    steps:
      - uses: actions/checkout@v7
      - uses: cachix/install-nix-action@v31
      - name: Find package names
        id: find-packages
        run: |
          packages=$(nix eval .#myPackages.x86_64-linux --apply builtins.attrNames --json | jq -c .)
          echo "packages=$packages" >> "$GITHUB_OUTPUT"

  build-packages:
    needs: find-packages
    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJSON(needs.find-packages.outputs.packages) }}
        system:
          - x86_64-linux
          - aarch64-linux
        include:
          - system: x86_64-linux
            runner: ubuntu-latest
          - system: aarch64-linux
            runner: ubuntu-26.04-arm
        
    uses: ./.github/workflows/build-with-attic.yml
    with:
      runs-on: ${{ matrix.runner }}
      target: ".#packages.${{ matrix.system }}.${{ matrix.package }}"
    secrets:
      GITHUB_ACCESS_TOKEN: ${{ secrets.READ_NIXOS_SECRETS_GITHUB_TOKEN }}
      TS_OAUTH_CLIENT_ID: ${{ secrets.TS_OAUTH_CLIENT_ID }}
      TS_OAUTH_SECRET: ${{ secrets.TS_OAUTH_SECRET }}
      ATTIC_TOKEN: ${{ secrets.ATTIC_TOKEN }} 
