name: build

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - target: "steadfast-dart"
            attr: ".#nixosConfigurations.steadfast-dart.config.system.build.toplevel"
            runner: ubuntu-latest
          - target: "steadfast-defender"
            attr: ".#nixosConfigurations.steadfast-defender.config.system.build.toplevel"
            runner: ubuntu-latest
          - target: "iso-aarch64"
            attr: ".#packages.aarch64-linux.iso-system"
            runner: ubuntu-24.04-arm
          - target: "iso-x86_64"
            attr: ".#packages.x86_64-linux.iso-system"
            runner: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - uses: nixbuild/nix-quick-install-action@v35
        with:
          github_access_token: ${{ secrets.READ_NIXOS_SECRETS_GITHUB_TOKEN }}
          nix_conf: experimental-features = nix-command flakes

      - uses: DeterminateSystems/magic-nix-cache-action@v14

      - name: Build with Nix
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
        run: |
          nix build \
            ${{ matrix.attr }} \
            --print-build-logs \
            --no-link

  # Add to deployed branch if build succeeded and the push was on main
  promote:
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Fast-forward deployed branch
        run: |
          git push origin HEAD:refs/heads/deployed

