name: build

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - target: "steadfast-dart"
            attr: ".#nixosConfigurations.steadfast-dart.config.system.build.toplevel"
            runner: ubuntu-latest
          - target: "steadfast-defender"
            attr: ".#nixosConfigurations.steadfast-defender.config.system.build.toplevel"
            runner: ubuntu-latest
          - target: "iso-aarch64"
            attr: ".#packages.aarch64-linux.iso-system"
            runner: ubuntu-24.04-arm
          - target: "iso-x86_64"
            attr: ".#packages.x86_64-linux.iso-system"
            runner: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - uses: nixbuild/nix-quick-install-action@v35
        with:
          github_access_token: ${{ secrets.READ_NIXOS_SECRETS_GITHUB_TOKEN }}
          nix_conf: experimental-features = nix-command flakes

      - name: Tailscale
        uses: tailscale/github-action@v4.1.3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      - name: Cache Nix cache
        uses: actions/cache@v6.1.0
        with:
          path: ~/.cache/nix
          key: nix-cache-${{ runner.os }}-${{ hashFiles('flake.lock') }}-${{ hashFiles('**/*.nix') }}
          restore-keys: |
            nix-cache-${{ runner.os }}-${{ hashFiles('flake.lock') }}-
            nix-cache-${{ runner.os }}-
            nix-cache-

      - name: Build with Nix
        env:
          ATTIC_TOKEN: ${{ secrets.ATTIC_TOKEN }}
        run: |
          nix run nixpkgs#attic-client login local https://attic.osipol.uk "$ATTIC_TOKEN"
          nix run nixpkgs#attic-client use cache
          nix run nixpkgs#attic-client watch-store cache &
          watch_store_pid=$!
          trap 'kill "$watch_store_pid" 2>/dev/null || true; wait "$watch_store_pid" 2>/dev/null || true' EXIT

          nix build \
            ${{ matrix.attr }} \
            --print-build-logs \
            --no-link

  # Add to deployed branch if build succeeded and the push was on main
  promote:
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Fast-forward deployed branch
        run: |
          git push origin HEAD:refs/heads/deployed
