name: colmena

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  colmena:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: nixbuild/nix-quick-install-action@v35
        with:
          github_access_token: ${{ secrets.READ_NIXOS_SECRETS_GITHUB_TOKEN }}
          nix_conf: experimental-features = nix-command flakes

      - name: Start SSH agent
        uses: webfactory/ssh-agent@v0.10.0
        with:
          ssh-private-key: ${{ secrets.COLMENA_SSH_PRIVATE_KEY }}

      - name: Tailscale
        uses: tailscale/github-action@v4.1.3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      - name: Cache Nix store and cache
        uses: nix-community/cache-nix-action@v7
        with:
          primary-key: nix-${{ runner.os }}-${{ matrix.target }}-${{ hashFiles('**/flake.lock') }}-${{ hashFiles('**/*.nix') }}
          restore-prefixes-first-match: |
            nix-${{ runner.os }}-${{ matrix.target }}-${{ hashFiles('**/flake.lock') }}-
            nix-${{ runner.os }}-${{ matrix.target }}-
            nix-${{ runner.os }}-
          paths: |
            ~/.cache/nix
          gc-max-store-size-linux: 2G

      - name: Apply with Colmena
        env:
          ATTIC_TOKEN: ${{ secrets.ATTIC_TOKEN }}
        run: |
          nix run nixpkgs#attic-client login local https://attic.osipol.uk "$ATTIC_TOKEN"
          nix run nixpkgs#attic-client use cache

          # Upload new paths to cache while building
          nix run nixpkgs#attic-client watch-store cache &
          watch_store_pid=$!
          trap 'kill "$watch_store_pid" 2>/dev/null || true; wait "$watch_store_pid" 2>/dev/null || true' EXIT

          nix run .#colmena -- apply --no-build-on-target --keep-result --on @cloud

          # Push remaining paths to cache
          nix run nixpkgs#attic-client push cache .gcroots/*

