name: new nixbuild

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: nixbuild/nix-quick-install-action@v35
        with:
          github_access_token: ${{ secrets.READ_NIXOS_SECRETS_GITHUB_TOKEN }}
          nix_conf: experimental-features = nix-command flakes
          nix_on_tmpfs: true
      - name: Cache Nix cache
        uses: actions/cache@v6.1.0
        with:
          path: ~/.cache/nix
          key: nix-cache-${{ runner.os }}-${{ hashFiles('flake.lock') }}-${{ hashFiles('**/*.nix') }}
          restore-keys: |
            nix-cache-${{ runner.os }}-${{ hashFiles('flake.lock') }}-
            nix-cache-${{ runner.os }}-
            nix-cache-
      - uses: nixbuild/nixbuild-action@v25
        with:
          nixbuild_token: ${{ secrets.NIXBUILD_TOKEN }}
      - run: |
          nix build \
            .#nixosConfigurations.able-archer.config.system.build.toplevel \
            .#nixosConfigurations.steadfast-dart.config.system.build.toplevel \
            .#nixosConfigurations.steadfast-defender.config.system.build.toplevel \
            .#packages.aarch64-linux.iso-system \
            .#packages.x86_64-linux.iso-system \
            --print-build-logs \
            --eval-store auto \
            --store ssh-ng://eu.nixbuild.net \
            --builders "" \
            --no-link
  
  # Add to deployed branch if tests pass and the push was on main
  promote:
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Fast-forward deployed branch
        run: |
          git push origin HEAD:refs/heads/deployed

