name: Nix Flake Check

on:
  # Replaced by nixbuild
  workflow_dispatch:

jobs:
  nix-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7.0.0
      - name: Install Nix
        uses: cachix/install-nix-action@v31.10.6
        with:
          github_access_token: ${{ secrets.READ_NIXOS_SECRETS_GITHUB_TOKEN }}
      - name: Setup Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix flake check

