name: nixbuild

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: "able-archer"
            attr: ".#nixosConfigurations.able-archer.config.system.build.toplevel"
          - target: "steadfast-dart"
            attr: ".#nixosConfigurations.steadfast-dart.config.system.build.toplevel"
          - target: "steadfast-defender"
            attr: ".#nixosConfigurations.steadfast-defender.config.system.build.toplevel"
          - target: "iso-aarch64"
            attr: ".#packages.aarch64-linux.iso-system"
          - target: "iso-x86_64"
            attr: ".#packages.x86_64-linux.iso-system"

    steps:
      - uses: actions/checkout@v7
      - uses: nixbuild/nix-quick-install-action@v35
        with:
          github_access_token: ${{ secrets.READ_NIXOS_SECRETS_GITHUB_TOKEN }}
          nix_conf: experimental-features = nix-command flakes
          nix_on_tmpfs: true

      - name: Cache Nix store and cache
        uses: nix-community/cache-nix-action@v7
        with:
          primary-key: nix-${{ runner.os }}-${{ matrix.target }}-${{ hashFiles('**/flake.lock') }}-${{ hashFiles('**/*.nix') }}
          restore-prefixes-first-match: |
            nix-${{ runner.os }}-${{ matrix.target }}-${{ hashFiles('**/flake.lock') }}-
            nix-${{ runner.os }}-${{ matrix.target }}-
            nix-${{ runner.os }}-
          paths: |
            ~/.cache/nix

      - uses: nixbuild/nixbuild-action@v25
        with:
          nixbuild_token: ${{ secrets.NIXBUILD_TOKEN }}

      # Build matrix target
      - run: |
          nix build \
            ${{ matrix.attr }} \
            --print-build-logs \
            --eval-store auto \
            --store ssh-ng://eu.nixbuild.net \
            --builders ""
  
  # Add to deployed branch if tests pass and the push was on main
  promote:
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Fast-forward deployed branch
        run: |
          git push origin HEAD:refs/heads/deployed

