name: nixbuild

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  build:
    uses: nixbuild/nixbuild-action/.github/workflows/ci-workflow.yml@v25
    secrets:
      nixbuild_token: ${{ secrets.NIXBUILD_TOKEN }}
      github_access_token: ${{ secrets.READ_NIXOS_SECRETS_GITHUB_TOKEN }}
    with:
      # Run all checks, build all packages (including NixOS systems and ISOs)
      filter_builds: '.top_attr == "checks" or .top_attr == "packages"'

