name: Run with Attic

on:
  workflow_call:
    inputs:
      runs-on:
        description: What runner to run this workflow on.
        required: true
        type: string
      server:
        description: Attic server URL
        required: false
        default: https://attic.osipol.uk
        type: string
      cache:
        description: Attic cache name
        required: false
        default: cache
        type: string
      cache-public-key:
        description: Attic trusted public key
        required: false
        default: cache:C3spwmruXebNeOwAnYy98JGgTOnos586oMVmkYn/RYg=
        type: string
      script:
        description: The script to run.
        required: true
        type: string
    secrets:
      GITHUB_ACCESS_TOKEN:
      TS_OAUTH_CLIENT_ID:
        required: true
      TS_OAUTH_SECRET:
        required: true
      ATTIC_TOKEN:
        required: true

jobs:
  run-with-attic:
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: actions/checkout@v7
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_ACCESS_TOKEN }}
          extra_nix_config: |
            extra-substituters = ${{ inputs.server }}/cache
            extra-trusted-public-keys = ${{ inputs.cache-public-key }}

      - name: Tailscale
        uses: tailscale/github-action@v4.1.3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      - name: Configure Attic cache
        uses: ./.github/actions/attic-cache
        with:
          token: ${{ secrets.ATTIC_TOKEN }}

      - name: Run script
        id: stdout
        env:
          SCRIPT: ${{ inputs.script }}
        run: |
          bash -c "$USER_SCRIPT" >> "$GITHUB_OUTPUT" 

