name: Test ISO
description: Boot the x86_64 ISO & push successful tests to binary cache

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  # Consider another way of not re-running when the ISO wasn't changed than pushing to Attic cache
  # Also consider whether this test is really necessary
  test-iso:
    # Only run on flake update PRs
    if: >-
      github.event_name != 'pull_request' ||
      (
        contains(github.event.pull_request.labels.*.name, 'automated') &&
        contains(github.event.pull_request.labels.*.name, 'flake-update')
      )
    uses: ./.github/workflows/build-with-attic.yml
    with:
      runs-on: ubuntu-latest
      target: ".#packages.x86_64-linux.iso-boot-test"
    secrets:
      GITHUB_ACCESS_TOKEN: ${{ secrets.READ_NIXOS_SECRETS_GITHUB_TOKEN }}
      TS_OAUTH_CLIENT_ID: ${{ secrets.TS_OAUTH_CLIENT_ID }}
      TS_OAUTH_SECRET: ${{ secrets.TS_OAUTH_SECRET }}
      ATTIC_TOKEN: ${{ secrets.ATTIC_TOKEN }}
