name: Update Flake

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # run weekly on Sunday at midnight

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7.0.0
      - name: Install Determinate Nix
        uses: DeterminateSystems/determinate-nix-action@v3
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@main
        with:
          token: ${{ secrets.GH_TOKEN_FOR_UPDATES }}
          pr-title: "Update Nix flake inputs"
          pr-labels: |
            automated

