name: Update Dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 5' # run weekly on Friday at midnight

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7.0.1
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.READ_NIXOS_SECRETS_GITHUB_TOKEN }}

      - name: Update flake lock
        run: nix flake update --commit-lock-file --commit-lockfile-summary "updated flake.lock"

      - name: Update npins
        run: nix run nixpkgs#npins -- update

      - name: Update package hashes
        run: |
          nix run nixpkgs#nix-update -- \
            --flake filebrowser-quantum \
            --subpackage frontend \
            --version=skip

      - name: Create pull request
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ secrets.GH_TOKEN_FOR_UPDATES }}
          branch: update-dependencies-action
          commit-message: "chore: update dependencies"
          title: "Update dependencies"
          labels: |
            automated
            flake-update

